drivers/misc: mtk/pmic: v1/mt6359: fix unused variable error
../drivers/misc/mediatek/pmic/mt6359/v1/pmic_irq.c:357:6: error: unused variable 'len' [-Werror,-Wunused-variable] int len = 0; ^

Signed-off-by: Anupam Roy <github.769@gmail.com>